/*
 * 
 */
package com.datn.drone.controller;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

// TODO: Auto-generated Javadoc
/**
 * The Class SHA256.
 */
public class SHA256 {

	/**
	 * Gets the sha.
	 *
	 * @param input the input
	 * @return the sha
	 * @throws NoSuchAlgorithmException the no such algorithm exception
	 */
	public static byte[] getSHA(String input) throws NoSuchAlgorithmException {
		// Static getInstance method is called with hashing SHA
		MessageDigest md = MessageDigest.getInstance("SHA-256");

		// digest() method called
		// to calculate message digest of an input
		// and return array of byte
		return md.digest(input.getBytes(StandardCharsets.UTF_8));
	}

	/**
	 * To hex string.
	 *
	 * @param hash the hash
	 * @return the string
	 */
	public static String toHexString(byte[] hash) {
		// Convert byte array into signum representation
		BigInteger number = new BigInteger(1, hash);

		// Convert message digest into hex value
		StringBuilder hexString = new StringBuilder(number.toString(16));

		// Pad with leading zeros
		while (hexString.length() < 32) {
			hexString.insert(0, '0');
		}

		return hexString.toString();
	}

	// Driver code
//	public static void main(String args[]) {
//		try {
//			System.out.println("HashCode Generated by SHA-256 for:");
//
//			//code: 4b04eda6da42c280513808ea40aec0d9b21dc6d566247b848eac2c6370159dbb
//			String s1 = "5e8d98d5cb2a4b58b02d06ef.5e86f1ac56de7131e29ed61e";
//			System.out.println("S1: " + toHexString(getSHA(s1)));
//
//			//code: 1185dacf0d0399fd6722c57ac8448392c8c43b2fb7a25abce64b3782de78bf36
//			String s2 = "5e875aeb8c56ab1607f64e83.5e86f1ac56de7131e29ed61e";
//			System.out.println("\n S2: " + toHexString(getSHA(s2)));
//		}
//		// For specifying wrong message digest algorithms
//		catch (NoSuchAlgorithmException e) {
//			System.out.println("Exception thrown for incorrect algorithm: " + e);
//		}
//	}

}
